import { ValueObject } from '../../shared/base';

interface AIResponseProps {
  content: string;
  confidence: number;
  tokensUsed: number;
  modelUsed: string;
  processingTimeMs: number;
  citations?: string[];
}

/**
 * AI Response Value Object
 * Represents a response generated by the AI system
 */
export class AIResponse extends ValueObject<AIResponseProps> {
  private constructor(props: AIResponseProps) {
    super(props);
  }

  get content(): string {
    return this.props.content;
  }

  get confidence(): number {
    return this.props.confidence;
  }

  get tokensUsed(): number {
    return this.props.tokensUsed;
  }

  get modelUsed(): string {
    return this.props.modelUsed;
  }

  get processingTimeMs(): number {
    return this.props.processingTimeMs;
  }

  get citations(): string[] {
    return this.props.citations || [];
  }

  get isHighConfidence(): boolean {
    return this.props.confidence >= 0.8;
  }

  get isMediumConfidence(): boolean {
    return this.props.confidence >= 0.5 && this.props.confidence < 0.8;
  }

  get isLowConfidence(): boolean {
    return this.props.confidence < 0.5;
  }

  static create(
    content: string,
    confidence: number,
    tokensUsed: number,
    modelUsed: string,
    processingTimeMs: number,
    citations?: string[],
  ): AIResponse {
    if (confidence < 0 || confidence > 1) {
      throw new Error('Confidence must be between 0 and 1');
    }
    if (tokensUsed < 0) {
      throw new Error('Tokens used cannot be negative');
    }

    return new AIResponse({
      content,
      confidence,
      tokensUsed,
      modelUsed,
      processingTimeMs,
      citations,
    });
  }
}
